name: BuildUI
 
on: 
    push:
        branches: [main]
 
jobs:
  build:
 
    runs-on: windows-latest
    
    env:
      Solution_Name: AssistPurchaseFrontend/AssistPurchaseFrontend.sln
 
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build AssistPurchaseFrontend/AssistPurchaseFrontend.sln
